### ISSUE TITLE
Node should always be marked invisible before deallocating

### ISSUE THREAD

**Issue by Dominionys** [facebookarchive/AsyncDisplayKit#2252]
AsyncDisplayKit version - '1.9.90' 
'1.9.81' works fine.

Hi, can you help me with it? I have a ASTableNode on ViewController (not AS). For example i have 5 section with random number of rows, and if i will scroll table to bottom then to top and reloadSection (for example) 3 section (not on the screen), everything is good. But if i didn't scroll and reload table, app will crash. All nodes are layerBacked = false. 
Reload section: `self?.tableViewCompany.tableNode.view.reloadSections(indexSet, withRowAnimation: UITableViewRowAnimation.Fade)`
Cell example:`
class CompanyCellNodeItem: AbstractNodeCell {

```
var viewImage:          ASNetworkImageNode!
var viewLabelDate:      ASTextNode!
var viewLabelTitle:     ASTextNode!
var viewLabelSubtitle:  ASTextNode!
var isNeedTopView:      Bool           = true


init(type:CompanyInfo, separator:Bool) {
    super.init(separator: separator)

    viewImage = {
        let view = ASNetworkImageNode.with(Alpha:0.0, Mode:.ScaleToFill, Color:.whiteColor())
        view.layerBacked = false
        view.defaultImage = UIImage(named: "image_placeholder.png")
        view.preferredFrameSize = CGSize(width: 80, height: 50)
        return view
    }()

    viewLabelTitle = {
        let view = ASTextNode.init()
        view.layerBacked = false
        view.maximumNumberOfLines = 2
        return view
    }()

    viewLabelSubtitle = {
        let view = ASTextNode.init()
        view.layerBacked = false
        view.maximumNumberOfLines = 2
        return view
    }()

    viewLabelDate = {
        let view = ASTextNode.init()
        view.placeholderInsets = UIEdgeInsetsZero
        view.preferredFrameSize = CGSizeMake(30, 10)
        view.layerBacked = false
        view.attributedText = NSAttributedString.attributedCompanyItemDate("25.12.12")
        return view
    }()


    addSubnode(viewImage)
    addSubnode(viewLabelTitle)


    switch type {
    case .Gift:
        isNeedTopView = false
        addSubnode(viewLabelSubtitle)
    case .Event:
        addSubnode(viewLabelSubtitle)
    case .News:
        addSubnode(viewLabelDate)
    default:
        break
    }

}

override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {

    let spacer = ASLayoutSpec()
    spacer.flexGrow = true

    let layoutHorizontalDateInfo = ASStackLayoutSpec(
        direction: .Horizontal,
        spacing: 0,
        justifyContent: .Start,
        alignItems: .Start,
        children: [viewLabelDate ,spacer])

    viewLabelTitle.spacingAfter   = 3.0

    let verticalChildren:[ASLayoutable] = isNeedTopView ?
                                           [layoutHorizontalDateInfo,viewLabelTitle,viewLabelSubtitle]
                                         : [viewLabelTitle,viewLabelSubtitle]


    let layoutVertical = ASStackLayoutSpec(
        direction: .Vertical,
        spacing: 0,
        justifyContent: .Center,
        alignItems: .Stretch,
        children: verticalChildren)

    layoutVertical.flexShrink = true
    layoutVertical.flexGrow   = true
    layoutVertical.alignSelf  = .Center

    let layoutHorizontalMain =  ASStackLayoutSpec(
        direction: .Horizontal,
        spacing: 15,
        justifyContent: .Start,
        alignItems: .Start,
        children: [ viewImage, layoutVertical,viewImageArrow ])

    layoutHorizontalMain.spacingAfter  = 8
    layoutHorizontalMain.spacingBefore = 8
    let layoutSeparator = self.addTopSeparator(layoutHorizontalMain)

    return self.addDefaultEdgeInsets(layoutSeparator)
}
```

`

Trace log: `2016-09-15 18:35:10.694 Prestige[3690:1807714] *** Assertion failure in -[Prestige.CompanyNodeNew dealloc], /Users/Unfeeling/XcodeProjects/Pods/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:382
2016-09-15 18:35:10.700 Prestige[3690:1807714] *** Assertion failure in -[ASImageNode dealloc], /Users/Unfeeling/XcodeProjects/Pods/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:382
2016-09-15 18:35:10.703 target[3690:1807714] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Node should always be marked invisible before deallocating; interfaceState: 15, <ASImageNode: 0x173da200>'
*** First throw call stack:
(0x254e391b 0x24c7ee17 0x254e37f1 0x25cc7529 0xb3977d 0xb72415 0xb1dcd9 0xacb3bb 0xac8da3 0x29d617d1 0x29a5621b 0x29a591b5 0xb56251 0x24c7df55 0x24c87ddf 0x24c87e03 0xb39ab9 0xb1dcd9 0x253fad99 0x24c98f67 0x253fad99 0x24c98f67 0x24c993a9 0x253f2f89 0x254a406f 0x253f3229 0x253f3015 0x269e3ac9 0x29ac5189 0x3d2770 0x2509b873)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by hannahmbanana** [comment]
@Denis1992: It's odd that this has regressed between 1.9.81 and 1.9.90. A few questions:

- Is this 100% reproducible? 
- Could you see if it is reproducible on our `releases/p6.13` branch (stable version of ASDK that Pinterest ships with - has a few small API changes so we haven't released a cocoapod yet). It should be easy to point your podfile to this branch and run pod update.

**Comment by hannahmbanana** [comment]
@Dominionys - Are you still seeing this issue?

**Comment by hannahmbanana** [comment]
@Dominionys - Are you still seeing this issue? I'm going to close this issue given the length of time since the thread was active. Feel free to re-open the issue if you are still having this issue.

**Comment by nhatlee** [comment]
I still got the same crash on SDK version beta 2.
my code:
`func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let _view = UIView(frame: CGRect(x: 0, y: 0, width: self.view.frame.size.width, height: 50))
        let textNode = ASTextNode()
        textNode.isLayerBacked = true
        textNode.backgroundColor = UIColor.clear
        textNode.attributedText = NSAttributedString(
            string: "All Categories",
            attributes: [
                NSFontAttributeName: UIFont.systemFont(ofSize: 20),
                NSForegroundColorAttributeName: UIColor.black,
                NSKernAttributeName: -0.3
            ])
        _view.addSubnode(textNode)
        return _view
    }`
The crash log:
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Node should always be marked invisible before deallocating. Node: <ASTextNode: 0x7fb08d01b000; text = "All Categories">'`

**Comment by hannahmbanana** [comment]
@nhatlee - thank you for reporting! Is this issue 100% reproducible for you? Would it be possible for you to include a sample project here or emailed to asyncdisplaykit@gmail.com?  

cc @Adlai-Holler

**Comment by tomizimobile** [comment]
@hannahmbanana @Adlai-Holler I've also come across this issue. I found it in a specific view controller of mine, and I think having a non-translucent tabBar might be part of the issue (at least for me). Using aa9dff00de3b5faea432504aebfca1024108b727. Just run the sample project and hit the reload button without scrolling. Seems to be happening across a variety of simulators, tried it on 5S, 6S and 6S+

[ASDK-crash.zip](https://github.com/facebook/AsyncDisplayKit/files/620113/ASDK-crash.zip)

**Comment by Adlai-Holler** [comment]
@tomizimobile Thanks for an excellent repro! I turned it into a unit test case and resolved the issue in the linked PR. Could you and @nhatlee verify that the issue is fixed?

**Comment by tomizimobile** [comment]
@Adlai-Holler I'm still seeing the issue in my current project. I've been trying to recreate it in a separate project but haven't been able to reproduce it there so far.

**Comment by tomizimobile** [comment]
@Adlai-Holler alright, finally tracked it down. Seemed to be ok with a grouped tableView, but this is happening with a plain tableView.

[ASDK-crash.zip](https://github.com/facebook/AsyncDisplayKit/files/622810/ASDK-crash.zip)

**Comment by stephenkopylov** [comment]
Have the same issue with plain tv + section header views. 
Grouped tv works fine

**Comment by 9you** [comment]
I still facing this problem on `Texture 2.3`

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#145
