### ISSUE TITLE
[ASMultiplexImageNode] Sometimes the high-res image is not loaded automatically (works with manual -setNeedsDisplay).

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#882]
@appleguy This may be fixed in your working window PR, but I encountered a tough case today. I have a table view whose content is pretty static, and its cells contain multiplex image nodes. Seemingly at random after a lot of browsing around, I got into a state like this:

```
ASMultiplexImageNode. Showing low-res image on screen.
    loadedImageIdentifier: {high-res ID}
    displayedImageIdentifier: {low-res ID}
    image: {high-res image}
    contents: {low-res image}
    loadingImageIdentifier: nil
    displaySuspended: false
    layer.needsDisplay: false
```

No threads were doing anything interesting. Since `ASImageNode.image` was set correctly, the multiplex logic seems to be working right.

The `ASImageNode` hadn't displayed since getting the high res image set. I ran `po [imageNode setNeedsDisplay]` and sure enough, the image node re-rendered at full-res.  Maybe the range controller suppressed a display and then forgot to come back and redo it?

I'm currently trying to think of a workaround because these blurry images are in a build for investors. ~~I'm thinking I'll override `willEnterHierarchy` and, with some leeway, make sure that the node has been/will be displayed soon.~~

EDIT: I've come up with a workaround in my app. In our multiplex image node subclass, we do:

``` swift
override func willEnterHierarchy() {
    super.willEnterHierarchy()
    // Currently we will get added to a range controller's "working window" for pre-rendering. No need to attempt workaround until we're in a real window.
    let isWorkingWindow = layer.rootLayer.bounds == .zero
    if !isWorkingWindow {
        dispatch(after: 0.5) { [weak self] in
            self?.applyMissedRenderWorkaround()
        }
    }
}

private func applyMissedRenderWorkaround() {
    assert(NSThread.isMainThread())

    /// Workaround a rare issue in ASDK 1.9.1 where I may fail to render my most recent loaded image. https://github.com/facebook/AsyncDisplayKit/issues/882
    if let loadedID = loadedImageIdentifier where inHierarchy && !layer.needsDisplay() && !loadedID.isEqual(displayedImageIdentifier) {
        NSLog("WARNING: \(self) entered hierarchy without having rendered its high-res image. Marking as needs render…")
        setNeedsDisplay()
    }
}

extension CALayer {
    var rootLayer: CALayer {
        return superlayer?.rootLayer ?? self
    }
}
```

**Comment by appleguy** [comment]
@Adlai-Holler How long does it take to reproduce this condition?  Are there any known steps, such as it seems to occur after a high velocity scroll and then panning backwards into the area recently scrolled past?

Does your app set all of the image identifiers at once, or does it add / change them later?  In this case, do you always see the low-res image or is there sometimes no image at all?

**Comment by appleguy** [comment]
Also importantly: has this been observed with any other type of subnode, whether a regular ASImageNode, ASTextNode, or otherwise?  I'm going to rename this to reference Multiplex as it seems likely the issue is specific to that more complex class, but the moment we have an indication that it is more general, we should further clarify the name (and indeed that information would helpfully steer the investigation).

**Comment by Adlai-Holler** [comment]
@appleguy With long feeds of content, this condition will usually pop up after a couple minutes of browsing around. Haven't determined repro steps yet. It sets all the identifiers at once. Sometimes no image is showing, sometimes a low-res one. It has only been observed on multiplex so far but we do not use `ASImageNode` except when we set the image immediately after initialization.

I believe this is more general that ASMultiplexImageNode because there appears to be no way to set `ASImageNode.image` without triggering a display pass. And since the image was set to the high-res data, the multiplex node's job was done. That said, I understand why you don't want to expand the search scope needlessly.

**Comment by appleguy** [comment]
@Adlai-Holler was this fixed with your changes / should we close this?

**Comment by Adlai-Holler** [comment]
Yep this is handled.

**Comment by Adlai-Holler** [comment]
Well nope, this issue is still present now that I'm using multiple image identifiers in my multiplex nodes again. Same condition – somehow we get into this state:

```
ASMultiplexImageNode. Showing low-res image on screen.
    loadedImageIdentifier: {high-res ID}
    displayedImageIdentifier: {low-res ID}
    image: {high-res image}
    contents: {low-res image}
    loadingImageIdentifier: nil
    displaySuspended: false
    layer.needsDisplay: false
```

Here are the logs of that particular multiplex image node's loading history:

```
2016-05-07 13:59:37.439 Best immediately available image identifier is (null)
2016-05-07 13:59:37.439 Loading next image, ident: (loader)
2016-05-07 13:59:37.476 Acquired next image ((loader)) from data-source
2016-05-07 13:59:37.484 loaded -> displaying ((loader), <UIImage: 0x16233dbb0>, {192, 252})
2016-05-07 13:59:37.485 Loading next image, ident: (real image)
2016-05-07 13:59:39.210 Best immediately available image identifier is (loader)
2016-05-07 13:59:39.210 loaded -> displaying ((loader), <UIImage: 0x16233dbb0>, {192, 252})
2016-05-07 13:59:39.211 Loading next image, ident: (real image)
2016-05-07 13:59:39.397 Best immediately available image identifier is (loader)
2016-05-07 13:59:39.398 loaded -> displaying ((loader), <UIImage: 0x16233dbb0>, {192, 252})
2016-05-07 13:59:39.398 Loading next image, ident: (real image)
2016-05-07 13:59:39.595 Acquired next image ((real image)) from download
2016-05-07 13:59:39.595 loaded -> displaying ((real image), <UIImage: 0x16257e090>, {750, 1000})
2016-05-07 13:59:39.595 Best immediately available image identifier is (real image)
2016-05-07 13:59:39.596 loaded -> displaying ((real image), <UIImage: 0x16257e090>, {750, 1000})
```

The last two lines are kind of bad – `displayWillStart:` is calling out to `fetchData` which is synchronously re-fetching the image we just got – but I believe `ASImageNode` will correctly ignore the image update since the images are identical, so it may not be the cause of this problem. Do you agree we should consider removing the `fetchData` call from `displayWillStart`? If so, do you see any "gotchas" there that I should think about as I tackle it?

Otherwise, I'm going to keep digging. Log ALL the things! @appleguy

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#111
